### ISSUE TITLE
Contributions?

### ISSUE THREAD

**Issue by barryels** [sebastiansandqvist/mithril-examples#1]
Hi @sebastiansandqvist, are you accepting contributions for this project? I think it's an awesome bite-sized showcase of Mithril and I would love to help grow this project.

**Comment by sebastiansandqvist** [comment]
Absolutely, I think that'd be great. Since I don't have a formal contributing guide, I think the best way would be to start with a github issue to make sure the idea fits in with what's on the site now. I'm also looking into other ways of displaying the examples, so for most parts of this project I'm open to improvements and additions.

**Comment by sebastiansandqvist** [comment]
I've added a small guide to the readme and changed the folder structure of the examples so that it is (I hope) a bit easier to contribute now.

**Comment by barryels** [comment]
Perfect! :+1:
